
name: QTC For HarmonyOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-server
    steps:
      - name: Set up proxy for Git
        run: |
          git config --global http.proxy http://localhost:7890
          git config --global https.proxy http://localhost:7890
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build
        shell: cmd
        run: |
          set QTFRAMEWORK_BYPASS_LICENSE_CHECK=1
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          call "A:\Qt\6.8.3\msvc2022_64\bin\qtenv2.bat"
          cd /d ${{ github.workspace }}
          cmake -S . -B ./build/ -DCMAKE_PREFIX_PATH=A:/Qt/6.8.3/msvc2022_64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
          cmake --build ./build/ --target all
          
    
